import { throwError } from "./throwError";

export function checkUserAuth(user) {
  if (!user) {
    throwError("No has iniciado sesi√≥n", {
      code: "UNAUTHENTICATED",
    });
  }
}
